Repository wecode-bootcamp-korea/35-1st-kleenex-frontend, pull requests merged in 2022-07, with the labels that each got.

#2 [35기 오창훈] Add: ProductCard 컴포넌트 구현
  package-lock.json
  package.json
  public/data/productCard.json
  public/images/kingkong-fizzy-summer-thumbnail.png
  src/components/ProductCard/ProductCard.js
  src/components/ProductCard/ProductCard.scss
Labels: 멘토 리뷰 요청

#6 [35기 김영수] ADD : Nav 레이아웃 구현 완료
  public/images/Nav/NavLogo.JPG
  public/images/Nav/NavSmallLogo.png
  public/images/Nav/icon1.png
  public/images/Nav/icon2.png
  public/images/Nav/icon3.png
  public/images/Nav/icon4.png
  public/images/Nav/search.png
  public/images/cover-instagram3.png
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavSmall.js
  src/components/Nav/NavSmall.scss
Labels: 완료

#7 [35기 오창훈] Modify: footer 컴포넌트 브랜치명 수정 및 상수 데이터 분리
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterDataList.js
Labels: 멘토 리뷰 요청

#5 [35기 최원익] Add: login 기본 레이아웃 및 유효성 검사기능 추가, 아이디 저장기능 구현
  src/Router.js
  src/pages/Login/Login.js
  src/pages/Login/login.scss
Labels: 완료

#10 [35기 오창훈] Modify: ProductCard 컴포넌트 마이너 수정
  src/components/ProductCard/ProductCard.js
  src/components/ProductCard/ProductCard.scss
Labels: 완료

#9 [35기 오창훈] Modify: Footer 컴포넌트 마이너 수정 완료
  src/components/Footer/Footer.js
  src/components/Footer/FooterData.js
Labels: 완료

#13 [35기 오창훈] Add: ProductsList 컴포넌트 레이아웃 및 기능 구현
  public/data/productDataList.json
  src/components/ProductsList/ProductsList.js
  src/components/ProductsList/ProductsList.scss
Labels: 완료

#15 [35기 오창훈] Add: Buttons 컴포넌트 레이아웃 및 기능 구현
  src/components/Buttons/Buttons.js
  src/components/Buttons/Buttons.scss
Labels: 완료

#12 [35기 오창훈] Add: Products 페이지 레이아웃 및 기능 구현
  src/Router.js
  src/pages/Products/Products.js
  src/pages/Products/Products.scss
  src/pages/Products/ProductsData.js
Labels: 완료

#14 [35기 오창훈] Add : ProductDetail 컴포넌트 레이아웃 구성 완료 및 로직 구현중
  public/data/productDataDetail.json
  src/components/ProductDetail/ProductDetail.js
  src/components/ProductDetail/ProductDetail.scss
Labels: 멘토 리뷰 요청

#19 [35기 최원익] Add : 회원가입 창으로 가는 navigate 추가
  src/pages/Login/Login.js
Labels: Conflict 해결 요청

#21 [35기 최원익] Fixed: cart 수량 변경 로직 수정
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/InProduct/InProduct.js
  src/pages/Login/Login.js
Labels: 완료
